### ISSUE TITLE
Chef::Exceptions::ContentLengthMismatch: Response body length 65536 does not match HTTP Content-Length header 88744.

### ISSUE THREAD

**Issue by dafyddcrosby** [chef/chef-provisioning#139]
Just updated to the latest chef and chef-metal, and there appears to be a problem with the HTTP validation:

```
[2014-08-23T16:48:24-06:00] DEBUG: ---- HTTP Status and Header Data: ----
[2014-08-23T16:48:24-06:00] DEBUG: HTTP 1.1 200 OK
[2014-08-23T16:48:24-06:00] DEBUG: content-type: application/json
[2014-08-23T16:48:24-06:00] DEBUG: server: chef-zero
[2014-08-23T16:48:24-06:00] DEBUG: date: Sat, 23 Aug 2014 22:48:24 GMT
[2014-08-23T16:48:24-06:00] DEBUG: content-length: 88744
[2014-08-23T16:48:24-06:00] DEBUG: connection: close
[2014-08-23T16:48:24-06:00] DEBUG: ---- End HTTP Status/Header Data ----
[2014-08-23T16:48:24-06:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
[2014-08-23T16:48:24-06:00] INFO: HTTP Request Returned 200 OK : error

================================================================================
Chef encountered an error attempting to load the node data for "dcrosby"
================================================================================

Unexpected Error:
-----------------
Chef::Exceptions::ContentLengthMismatch: Response body length 65536 does not match HTTP Content-Length header 88744.

[2014-08-23T16:48:24-06:00] DEBUG: Re-raising exception: Chef::Exceptions::ContentLengthMismatch - Response body length 65536 does not match HTTP Content-Length header 88744.
/Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http/validate_content_length.rb:102:in `validate'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http/validate_content_length.rb:52:in `handle_response'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http.rb:229:in `block in apply_response_middleware'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http.rb:227:in `each'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http.rb:227:in `inject'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http.rb:227:in `apply_response_middleware'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/http.rb:144:in `request'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/rest.rb:115:in `get'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/node.rb:508:in `load'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/node.rb:492:in `find_or_create'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/policy_builder/expand_node_object.rb:92:in `load_node'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/client.rb:249:in `load_node'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/client.rb:418:in `do_run'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/client.rb:213:in `block in run'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/client.rb:207:in `fork'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/client.rb:207:in `run'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/application.rb:236:in `run_chef_client'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/application/client.rb:338:in `block in run_application'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/application/client.rb:327:in `loop'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/application/client.rb:327:in `run_application'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/lib/chef/application.rb:55:in `run'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/gems/chef-11.14.6/bin/chef-client:26:in `<top (required)>'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/bin/chef-client:23:in `load'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/bin/chef-client:23:in `<main>'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/bin/ruby_executable_hooks:15:in `eval'
  /Users/dcrosby/.rvm/gems/ruby-2.0.0-p0/bin/ruby_executable_hooks:15:in `<main>'
[2014-08-23T16:48:24-06:00] FATAL: Stacktrace dumped to /Users/dcrosby/.chef/local-mode-cache/cache/chef-stacktrace.out
```

From the little debugging I've done so far with pry, I think this might be an issue where the receiver truncates the message - possibly a Ruby issue? Sorry I haven't had more time to dig, kind of caught me by surprise end of day (on a weekend ;-)

**Comment by joshzitting** [comment]
we have seen this same issue in a few different runs also... They happen on different machines but if you run the recipe again it passes. only happens occasionally.
