### ISSUE TITLE
Convergence error - Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by dvlscm** [chef/chef-provisioning#154]
Without going too deep into the details, I'm trying to create machines with Metal, then provision them later. The first task runs `chef-client -z` with a file like so:

``` ruby
require 'chef_metal'
with_driver 'fog:AWS', :compute_options => { :aws_access_key_id => '...', :aws_secret_access_key => '...' }
machine_batch do
  machine 'box1' do
    machine_options :bootstrap_options => {
    :flavor_id => 'm3.medium',
    :key_name => 'keyname',
    :groups => ['groupname'],
    :image_id => 'ami-4aa27022'
    }
    action :allocate
  end
end
```

That works fine. AWS shows my machine. The second task runs `chef-client -z` with a file like so:

``` ruby
require 'chef_metal'
with_driver 'fog:AWS', :compute_options => { :aws_access_key_id => '...', :aws_secret_access_key => '...' }
machine_batch do
  machine 'box1' do
    recipe 'stage'
    action :converge
  end
end
```

That gives me this error:

```
===============================================================================
Chef encountered an error attempting to load the node data for "darkcastle.local"
===============================================================================

Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.

Server Response:
----------------
Exception raised!  #<Errno::EACCES: Permission denied @ dir_s_mkdir - /nodes>
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:57:in `mkdir'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:57:in `block in create_child'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:55:in `each'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:55:in `create_child'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/chef_fs_data_store.rb:406:in `get_dir'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/chef_fs_data_store.rb:395:in `with_dir'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/chef_fs/chef_fs_data_store.rb:68:in `create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:56:in `block in create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:168:in `fix_exceptions'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:55:in `create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:92:in `create_data'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/endpoints/rest_list_endpoint.rb:30:in `post'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:29:in `call'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/rest_router.rb:23:in `call'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/server.rb:443:in `block in app'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

This looks like a Chef error, not necessarily a Metal one, but I'm not sure how they interact. I don't see why there should be any permission problem on the machine. I was able to connect fine to create the machine and to start provisioning it, but then it craps out while running a recipe (I assume).

Am I doing something wrong with my deferred provisioning? Perhaps the wrong actions somehow?

Here's the stacktrace from Metal, if that can provide a clue:

```
Generated at 2014-09-04 11:46:31 -0400
Net::HTTPFatalError: 500 "Internal Server Error "
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/http.rb:145:in `request'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/http.rb:126:in `post'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/node.rb:535:in `create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/node.rb:496:in `rescue in find_or_create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/node.rb:492:in `find_or_create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/policy_builder/expand_node_object.rb:92:in `load_node'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/client.rb:249:in `load_node'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/client.rb:418:in `do_run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/client.rb:213:in `block in run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/client.rb:207:in `fork'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/client.rb:207:in `run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/application.rb:236:in `run_chef_client'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/application/client.rb:338:in `block in run_application'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/application/client.rb:327:in `loop'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/application/client.rb:327:in `run_application'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/lib/chef/application.rb:55:in `run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.14.6/bin/chef-client:26:in `<top (required)>'
/Users/me/.rbenv/versions/2.1.2/bin/chef-client:23:in `load'
/Users/me/.rbenv/versions/2.1.2/bin/chef-client:23:in `<main>'
```

**Comment by StFS** [comment]
I'm seeing this happen also. I'm just beginning to get chef-provisioning to work but I'm not sure what chef zero uses as its "root". From the error message it looks like it's trying to create a directory "nodes" in the root of the filesystem which would fail of course. Should I be specifying a certain "chef zero root location"? And if so, how?

**Comment by kolebas** [comment]
The file "knife.rb" a parameter "node_path"
