### ISSUE TITLE
Provisioning machines at a later time after creating

### ISSUE THREAD

**Issue by dvlscm** [chef/chef-provisioning#156]
Based on advice from @jkeiser from some other issues I logged, I upgraded Chef to the latest available, which is `12.0.0.alpha.1`.

Here's my scenario. I want to create the machines (just one in this example) in a cluster initially. I do that with this code in a file called `test_create.rb`, using the `allocate` action:

``` ruby
require 'chef_metal'
with_driver 'fog:AWS', :compute_options => { :aws_access_key_id => '...', :aws_secret_access_key => '...' }
machine_batch do
  machine 'test1' do
    machine_options :bootstrap_options => {
      :flavor_id => 'm3.medium',
      :key_name => 'keyname',
      :groups => ['groupname'],
      :image_id => 'ami-4aa27022'
    }
    action :allocate
  end
end
```

That appears to run without an error, but it looks like the action running is `converge`, not `allocate`, so I have to wonder if I'm doing something wrong:

``` ruby
± chef-client -z /Users/me/.../pipe/test_create.rb
[2014-09-04T16:12:07-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.0.0.alpha.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      nokogiri (>= 1.4.0, ~> 1.5)
      uuidtools (~> 2.1.2)
      builder (>= 2.1.2)
      akami (~> 1.0)
      multi_json (>= 1.8.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[2014-09-04T16:12:10-04:00] WARN: Node darkcastle.local has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/me/.../pipe/test_create.rb
  * machine_batch[default] action converge
    - creating machine test1 on fog:AWS:...:
    -   flavor_id: "m3.medium"
    -   key_name: "keyname"
    -   groups: ["groupname"]
    -   image_id: "ami-4aa27022"
    - machine test1 created as i-ce3c2321 on fog:AWS:...:
    - [test1] create node test1 at http://localhost:8889
```

After I create the machines, I want to converge them at a (relatively) much later time. I did that with this code in an entirely separate file called `test_bake.rb`, referencing the `test1` machine by the same name I used when I created it:

``` ruby
require 'chef_metal'
with_driver 'fog:AWS', :compute_options => { :aws_access_key_id => '...', :aws_secret_access_key => '...' }
with_chef_local_server chef_repo_path: 'pipe', cookbook_path: 'cookbooks'

machine_batch do
  machine 'test1' do
    action :converge
    recipe 'book1::build_default'
  end
end
```

That didn't behave at all like I was expecting. I got this output:

```
± chef-client -z /Users/me/.../pipe/test_bake.rb
[2014-09-04T16:15:56-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.0.0.alpha.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      nokogiri (>= 1.4.0, ~> 1.5)
      uuidtools (~> 2.1.2)
      builder (>= 2.1.2)
      akami (~> 1.0)
      multi_json (>= 1.8.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[2014-09-04T16:15:59-04:00] WARN: Node darkcastle.local has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/me/.../pipe/test_bake.rb
  * machine_batch[default] action converge
    - creating machine test1 on fog:AWS:...:
    -   key_name: "metal_default"
    - machine test1 created as i-ce352a21 on fog:AWS:...:[2014-09-04T16:16:08-04:00] ERROR: #<Errno::ENOENT: No such file or directory @ dir_s_mkdir - /pipe/nodes>
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:57:in `mkdir'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:57:in `block in create_child'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:55:in `each'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb:55:in `create_child'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/chef_fs_data_store.rb:406:in `get_dir'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/chef_fs_data_store.rb:395:in `with_dir'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.0.0.alpha.1/lib/chef/chef_fs/chef_fs_data_store.rb:68:in `create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:56:in `block in create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:168:in `fix_exceptions'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:55:in `create'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:92:in `create_data'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/endpoints/rest_list_endpoint.rb:30:in `post'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:29:in `call'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/rest_router.rb:23:in `call'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-zero-2.2/lib/chef_zero/server.rb:443:in `block in app'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

    ===============================================================================
    Error executing action `converge` on resource 'machine_batch[default]'
===============================================================================
    Net::HTTPFatalError
    -------------------
    chef_node[test1] (basic_chef_client::block line 61) had an error: Net::HTTPFatalError: 500 "Internal Server Error "

    Resource Declaration:
    ---------------------
    # In /Users/me/.../pipe/test_bake.rb

      6: machine_batch do
      7:   machine 'test1' do
      8:     action :converge
      9:     recipe 'stage::default'
     10:   end
     11: end

    Compiled Resource:
    ------------------
    # Declared in /Users/me/.../pipe/test_bake.rb:6:in `from_file'

    machine_batch("default") do
      action :converge
      retries 0
      retry_delay 2
      guard_interpreter :default
      driver "fog:AWS"
      chef_server {:chef_server_url=>"http://127.0.0.1:8901", :options=>{}}
      cookbook_name "@recipe_files"
      recipe_name "/Users/me/.../pipe/test_bake.rb"
      machines ["test1"]
    end


Running handlers:
[2014-09-04T16:16:08-04:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-04T16:16:08-04:00] ERROR: Exception handlers complete
[2014-09-04T16:16:08-04:00] FATAL: Stacktrace dumped to /Users/me/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 11.336116 seconds
[2014-09-04T16:16:08-04:00] ERROR: machine_batch[default] (@recipe_files::/Users/me/.../pipe/test_bake.rb line 6) had an error: Net::HTTPFatalError: chef_node[test1] (basic_chef_client::block line 61) had an error: Net::HTTPFatalError: 500 "Internal Server Error "
[2014-09-04T16:16:08-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

That output raises several questions:
1) Why is my `machine_batch` with a `converge` action creating a machine when it already exists?

``` ruby
  * machine_batch[default] action converge
      - creating machine test1 on fog:AWS:...:
      -   key_name: "metal_default"
      - machine test1 created as i-ce352a21 on fog:AWS:...:
```

If I want to converge a machine later that I created before, does referencing that machine by the same name cut the mustard, or do I need to do something else to to mean "converge this machine I created a while ago"?

2) In that snippet above, it looks like the convergence is using the metal default key. That's not the key I created the machine with (see `test_create.rb` above). Do I need to specify the correct key again?

3) I see this error:

``` ruby
2014-09-04T16:16:08-04:00] ERROR: #<Errno::ENOENT: No such file or directory @ dir_s_mkdir - /pipe/nodes>
```

That makes me think I don't understand the way `chef_repo_path` should be working. I assumed it would specify a local directory where I want the JSON files for my cluster to go when I run chef-client. Is that right? It's certainly true, as the error says above, that I don't have a nodes directory in the `chef_repo_path` I gave to `with_chef_local_server`. Do I need to create that directory (and maybe `clients` too) manually?

4) Related to question three, is the `cookbook_path` I give to `with_chef_local_server` a directory relative to where I'm running `chef-client`? I assumed so, but dangerous things can happen when I assume.

5) I got a gnarly looking 500 error like so:

``` ruby
===============================================================================
    Error executing action `converge` on resource 'machine_batch[default]'
===============================================================================
    Net::HTTPFatalError
    -------------------
    chef_node[test1] (basic_chef_client::block line 61) had an error: Net::HTTPFatalError: 500 "Internal Server Error "
```

I have no idea what's causing this error, but the compiled resource in the error message looks kind of odd to me:

``` ruby
Compiled Resource:
    ------------------
    # Declared in /Users/me/.../pipe/test_bake.rb:6:in `from_file'

    machine_batch("default") do
      action :converge
      retries 0
      retry_delay 2
      guard_interpreter :default
      driver "fog:AWS"
      chef_server {:chef_server_url=>"http://127.0.0.1:8901", :options=>{}}
      cookbook_name "@recipe_files"
      recipe_name "/Users/me/.../pipe/test_bake.rb"
      machines ["test1"]
    end
```

The `cookbook_name` doesn't look like it has any relationship to the `cookbook_path` I gave to `with_chef_local_server`, so I wonder if I completely botched it somehow. Does that error suggest what I've done wrong?

Those are the questions that came to mind. Based on what I've heard in response to other issues, creating machines and then converging them later isn't out of bounds (even if those activities aren't in the same recipe?) Am I screwing something else up?

**Comment by abhishekamralkar** [comment]
@jkeiser I am getting below error while running my recipe 

```ERROR: machine_batch[default] (aa_cluster::softether_boot line 41) had an error: RuntimeError: Cannot move 'softether-000-dev' from fog:AWS:123456789012:us-west-2 to fog:AWS:908765432112:us-west-2: machine moving is not supported.  Destroy and recreate.
[2015-12-11T17:10:42+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)```
