### ISSUE TITLE
with_driver fails on second converge: Canonical driver ... has already been created!

### ISSUE THREAD

**Issue by justindossey** [chef/chef-provisioning#184]
I'm doing some simple metal tests.   I have written a recipe that does the following:

```ruby
require 'chef_metal'
vagrant_options = { ... }
with_machine_options(...)
with_driver('vagrant', foo: 1, bar: 2)
machine 'metal-vagrant-01' do
  converge true
end
```

chef-client -z converges this node correctly (empty run list for the node) but on the second converge (no changes to the recipe), I get the following error (sanitized):

```
==============================================================================
    Error executing action `converge` on resource 'machine[metal-vagrant-01]'
==============================================================================

    RuntimeError
    ------------
    Canonical driver vagrant:/Users/.../.chef/vms for vagrant has already been created!  Current options {:foo=>1, :bar=>2} would be ignored.
```

The backtrace:
```
/Users/.../.chefdk/gem/ruby/2.1.0/gems/chef-metal-0.14.2/lib/chef_metal/chef_run_data.rb:104:in `driver_for_url'
/Users/.../.chefdk/gem/ruby/2.1.0/gems/chef-metal-0.14.2/lib/chef_metal/chef_run_data.rb:78:in `driver_for'
/Users/.../.chefdk/gem/ruby/2.1.0/gems/chef-metal-0.14.2/lib/chef/provider/machine.rb:88:in `new_driver'
/Users/.../.chefdk/gem/ruby/2.1.0/gems/chef-metal-0.14.2/lib/chef/provider/machine.rb:20:in `block in <class:Machine>'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-11.14.0.rc.2/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-11.14.0.rc.2/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
```

The issue seems to be the use of `with_driver` with options.  

I get this with Vagrant as well as with EC2.

**Comment by jkeiser** [comment]
This blocks setting a full canonical URL in some cases--we merged https://github.com/opscode/chef-provisioning-aws/pull/81 even though the URL it creates is non-canonical, due to this.

When this is fixed, we need to fix that as well.

**Comment by tyler-ball** [comment]
This is referencing `chef_metal` so I'm going to close this.  Please file a new bug if you see something similar in the latest version of chef-provisioning!
