### ISSUE TITLE
machine_batch does not inherit option from with_machine_options

### ISSUE THREAD

**Issue by vinyar** [chef/chef-provisioning#277]
Really odd error since the error output shows that resource had the image_id as part of the resource.

recipe:
```ruby
with_machine_options({
  :bootstrap_options => {
    :instance_type => "t1.micro",
    :key_name => "alexv",
    :security_group_ids => ['sg-7c895119']
  },
  :ssh_username => "root",
  :image_id => "ami-b6bdde86"  # CentOS 6.5
})

machine_batch do
  3.upto(5) do |n|
    instance = "#{name}-webserver-#{n}"
    machine instance do
      recipe "webserver"
      tag "#{name}-webserver-#{n}"
      converge true
    end
  end
end
```

error:
```ruby
  * machine_batch[default] action converge
    - [alexv-webserver-3] update node alexv-webserver-3 at http://localhost:8889
    - [alexv-webserver-3]   update normal.tags from ["alexv-my-webserver-3"] to ["alexv-my-webserver-3", "my-webserver"]
    - creating machines alexv-webserver-4, alexv-webserver-5 on aws
    -   instance_type: "t1.micro"
    -   key_name: "alexv"
    -   security_group_ids: ["sg-7c895119"]
    ================================================================================
    Error executing action `converge` on resource 'machine_batch[default]'
    ================================================================================

    ArgumentError
    -------------
    missing required option image_id

    Resource Declaration:
    ---------------------
    # In /Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/local-mode-cache/cache/cookbooks/webserver/recipes/provision.rb

     48: machine_batch do
     49:   3.upto(5) do |n|
     50:     instance = "#{name}-webserver-#{n}"
     51:     machine instance do
     52:       recipe "webserver"
     53:       tag "my-webserver"
     54:     end
     55:  end
     56: end

    Compiled Resource:
    ------------------
    # Declared in /Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/local-mode-cache/cache/cookbooks/webserver/recipes/provision.rb:48:in `from_file'

    machine_batch("default") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      driver "aws"
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"alexv", :signing_key_filename=>"/Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/keys/chef_default"}}
      machine_options {:bootstrap_options=>{:instance_type=>"t1.micro", :key_name=>"alexv", :security_group_ids=>["sg-7c895119"]}, :ssh_username=>"root", :image_id=>"ami-b6bdde86"}
      declared_type :machine_batch
      cookbook_name "webserver"
      recipe_name "provision"
      machines ["alexv-webserver-3", "alexv-webserver-4", "alexv-webserver-5"]
    end


Running handlers:
[2015-02-09T06:10:34-08:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-09T06:10:34-08:00] ERROR: Exception handlers complete
[2015-02-09T06:10:34-08:00] FATAL: Stacktrace dumped to /Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 2 resources updated in 57.239237 seconds
[2015-02-09T06:10:34-08:00] ERROR: machine_batch[default] (webserver::provision line 48) had an error: ArgumentError: missing required option image_id
[2015-02-09T06:10:35-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
stack trace
```ruby
Generated at 2015-02-09 06:10:34 -0800
ArgumentError: machine_batch[default] (webserver::provision line 48) had an error: ArgumentError: missing required option image_id
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:593:in `block in validate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:592:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:592:in `validate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:601:in `request_params'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/query_request_builder.rb:37:in `populate_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:740:in `block (2 levels) in define_client_method'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:560:in `build_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:491:in `block (3 levels) in client_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/response.rb:175:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/response.rb:175:in `build_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/response.rb:114:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:203:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:203:in `new_response'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:490:in `block (2 levels) in client_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:391:in `log_client_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:477:in `block in client_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:373:in `return_or_raise'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `run_instances'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/ec2/instance_collection.rb:304:in `create'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-0.2.1/lib/chef/provisioning/aws_driver/driver.rb:745:in `block in create_many_instances'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:93:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

**Comment by vinyar** [comment]
This works, but it throws a new error relating to missing key - looks like the same thing just further down. 

On a side note, given that it fails, I would have expected it to fail in the compilation phase before any action took place.

```ruby
machine_batch 'bob' do
  1.upto(3) do |n|
    instance = "#{name}-webserver-#{n}"
    machine instance do
      machine_options bootstrap_options: { image_id: 'ami-b6bdde86' }
      recipe "webserver"
      tag "#{name}-webserver"

      # converge true
    end
  end
end
```

```ruby
    ================================================================================
    Error executing action `converge` on resource 'machine_batch[bob]'
    ================================================================================

    RuntimeError
    ------------
    No key found to connect to alexv-webserver-3 ({"driver_url"=>"aws", "driver_version"=>"0.2.1", "allocated_at"=>"2015-02-09 14:35:28 UTC", "host_node"=>"http://localhost:8889/nodes/", "image_id"=>"ami-b6bdde86", "instance_id"=>"i-84eeef8e"})!

    Resource Declaration:
    ---------------------
    # In /Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/local-mode-cache/cache/cookbooks/webserver/recipes/provision.rb

     48: machine_batch 'bob' do
     49:   1.upto(3) do |n|
     50:     instance = "#{name}-webserver-#{n}"
     51:     machine instance do
     52:       machine_options bootstrap_options: { image_id: 'ami-b6bdde86' }
     53:       recipe "webserver"
     54:       tag "#{name}-webserver"
     55:
     56:       # converge true
     57:     end
     58:   end
     59: end
     60:

    Compiled Resource:
    ------------------
    # Declared in /Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/local-mode-cache/cache/cookbooks/webserver/recipes/provision.rb:48:in `from_file'

    machine_batch("bob") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      driver "aws"
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"alexv", :signing_key_filename=>"/Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/keys/chef_default"}}
      machine_options {:bootstrap_options=>{:instance_type=>"t1.micro", :key_name=>"alexv", :security_group_ids=>["sg-7c895119"]}, :image_id=>"ami-b6bdde86", :ssh_username=>"root"}
      declared_type :machine_batch
      cookbook_name "webserver"
      recipe_name "provision"
      machines ["alexv-webserver-1", "alexv-webserver-2", "alexv-webserver-3"]
    end


Running handlers:
[2015-02-09T06:36:02-08:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-09T06:36:02-08:00] ERROR: Exception handlers complete
[2015-02-09T06:36:02-08:00] FATAL: Stacktrace dumped to /Users/alexvinyar/Documents/Projects/chef-provisioning/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 43.642909 seconds
[2015-02-09T06:36:03-08:00] ERROR: machine_batch[bob] (webserver::provision line 48) had an error: RuntimeError: No key found to connect to alexv-webserver-3 ({"driver_url"=>"aws", "driver_version"=>"0.2.1", "allocated_at"=>"2015-02-09 14:35:28 UTC", "host_node"=>"http://localhost:8889/nodes/", "image_id"=>"ami-b6bdde86", "instance_id"=>"i-84eeef8e"})!
[2015-02-09T06:36:03-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by vinyar** [comment]
btw: specifying all of the options seems to work.

**Comment by jkeiser** [comment]
@vinyar I merged a fix to chef-provisioning-aws very recently that affected images in batches ... would you mind pulling from master to see if that fixes you?

**Comment by jkeiser** [comment]
@smford22 verified latest master of AWS works, so I'm closing this resolved.  Please reopen if master of chef-provisioning-aws doesn't do it for you :)  I'll get an official release out today.
