### ISSUE TITLE
Can not destroy load balancers

### ISSUE THREAD

**Issue by danieljimenez** [chef/chef-provisioning#307]
```
    ================================================================================
    Error executing action `destroy` on resource 'load_balancer[skylab-app]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `destroy_load_balancer' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /Users/djimenez/Development/metal/recipes/destroy_all.rb
    
      8: load_balancer 'skylab-app' do
      9:   action :destroy
     10: end
    
    Compiled Resource:
    ------------------
    # Declared in /Users/djimenez/Development/metal/recipes/destroy_all.rb:8:in `from_file'
    
    load_balancer("skylab-app") do
      action [:destroy]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"wtfbox", :signing_key_filename=>nil}}
      declared_type :load_balancer
      cookbook_name "@recipe_files"
      recipe_name "/Users/djimenez/Development/metal/recipes/destroy_all.rb"
    end
```

**Comment by danieljimenez** [comment]
This is running on master chef-provisioning with the chef-provisioning-aws driver.

**Comment by jkeiser** [comment]
This is fixed on master.

**Comment by danieljimenez** [comment]
You are a gentleman and a scholar.

**Comment by danieljimenez** [comment]
Hm, I seem to still be getting the same error.

```
calculon:metal djimenez$ bundle list | grep -i chef
  * chef (12.1.1)
  * chef-provisioning (0.19 37b53d5)
  * chef-provisioning-aws (0.4.0 27f4b4b)
  * chef-zero (4.0)
  * cheffish (0.10)
```

**Comment by danieljimenez** [comment]
```
Recipe: @recipe_files::/Users/djimenez/Development/metal/recipes/destroy_all.rb
  * load_balancer[skylab-app] action destroy
    
    ================================================================================
    Error executing action `destroy` on resource 'load_balancer[skylab-app]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `destroy_load_balancer' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /Users/djimenez/Development/metal/recipes/destroy_all.rb
    
      7: load_balancer 'skylab-app' do
      8:   action :destroy
      9: end
     10: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/djimenez/Development/metal/recipes/destroy_all.rb:7:in `from_file'
    
    load_balancer("skylab-app") do
      action [:destroy]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"calculon.center.foreflight.com", :signing_key_filename=>nil}}
      declared_type :load_balancer
      cookbook_name "@recipe_files"
      recipe_name "/Users/djimenez/Development/metal/recipes/destroy_all.rb"
    end
    
[2015-03-21T22:27:17-05:00] ERROR: Converge failed with error message load_balancer[skylab-app] (@recipe_files::/Users/djimenez/Development/metal/recipes/destroy_all.rb line 7) had an error: NoMethodError: undefined method `destroy_load_balancer' for nil:NilClass
```
