### ISSUE TITLE
Second run fails using Vagrant (problem in InstallCached strategy)

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning#308]
Using chef-provisioning-vagrant on the second run I get:

```
Generated at 2015-03-23 11:26:38 -0500
NameError: machine[dbserver] (@recipe_files::/home/christine/git/topo-provision/gen/vagrant_deploy.rb line 10) had an error: NameError: undefined local variable or method `chef_version' for #<Chef::Provisioning::ConvergenceStrategy::InstallCached:0x00000004365958>
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning/convergence_strategy/install_cached.rb:53:in `setup_convergence'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
<snip>
```

Pretty sure https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_cached.rb#L53 should be:
```
 if !@chef_version
```

not `if !chef_version`. Or add an attr_reader.

**Comment by jkeiser** [comment]
This is fixed :)
