### ISSUE TITLE
machine_batch :destroy may be creating additional threads which result in NoMethodError

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning#319]
```ruby
# single machine works
machine 'a' do
  action [ :allocate, :destroy ]
end
```

```ruby
# batch fails with multiple machines
machine_batch do
  action [ :allocate, :destroy ]
  machines 'a', 'b'
end
```

```ruby
# batch fails with single machine
machine_batch do
  action [ :allocate, :destroy ]
  machines 'a'
end
```

```
NoMethodError: machine_batch[default2] (qa-chef-server-cluster::destroy-test line 16) had an error: NoMethodError: undefined method `call' for nil:NilClass
/usr/local/lib/ruby/gems/2.2.0/gems/chef-12.2.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:269:in `process_input'
/usr/local/lib/ruby/gems/2.2.0/gems/chef-12.2.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
/usr/local/lib/ruby/gems/2.2.0/gems/chef-12.2.1/lib/chef/chef_fs/parallelizer.rb:93:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/chef-12.2.1/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

**Comment by patrick-wright** [comment]
@tyler-ball

**Comment by patrick-wright** [comment]
This looks possibly related: https://github.com/chef/chef-provisioning/commit/9b595c7c43415853412c9e90f04b12057fb6e41d

**Comment by patrick-wright** [comment]
I removed lines 80-82 in the machine_batch provider and this fixed the issue.
```ruby
  action :destroy do
    parallel_do(by_current_driver) do |driver, specs_and_options|
      driver.destroy_machines(action_handler, specs_and_options, parallelizer)
      # parallel_do(specs_and_options.keys).each do |machine_spec|
      #   machine_spec.delete(action_handler)
      # end
    end
  end
```

**Comment by tyler-ball** [comment]
We'll still need the `machine_spec.delete` line - but you look on the right track.  Nested parallel_dos are probably not right!

**Comment by tyler-ball** [comment]
@patrick-wright If you want to open a PR for the fix, I think it should look like:
```ruby
  action :destroy do
    parallel_do(by_current_driver) do |driver, specs_and_options|
      driver.destroy_machines(action_handler, specs_and_options, parallelizer)
      specs_and_options.keys.each do |machine_spec|
        machine_spec.delete(action_handler)
      end
    end
  end
```

If you don't have time, I'll get to this when I do

**Comment by patrick-wright** [comment]
https://github.com/chef/chef-provisioning/pull/321

**Comment by tyler-ball** [comment]
Merged as https://github.com/chef/chef-provisioning/pull/321
