### ISSUE TITLE
NoMethodError: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by b-slim** [chef/chef-provisioning#329]
Hi Guys,
I am trying to use chef provisioning.
In my use case i am planing on using a actual remote chef-server.
Trying to run a simple example to provision a node and bootstrap it into my organization.
`bundle exec chef-client cluster.rb -c knife.rb` (from my local workstation)
Provisioning works ok but bootstraping doesn't work.
 i am using 

```
chef (12.2.1, 12.0.3)
chef-dk (0.4.0)
chef-metal (0.15)
chef-metal-fog (0.9)
chef-provisioning (1.1.0)
chef-provisioning-aws (0.4.0, 0.2.1)
chef-provisioning-azure (0.2.1, 0.1)
chef-provisioning-fog (0.13.3)
chef-provisioning-vagrant (0.8.2, 0.8.1)
chef-vault (2.5.0, 2.4.0)
chef-zero (4.2.1, 3.2.1, 1.5.6)
cheffish (1.1.2, 0.9.2)
chefspec (4.2.0, 4.0.2, 3.4.0, 1.3.1)
minitest-chef-handler (1.0.3)
```

this is the stack 

``` ruby
Generated at 2015-04-22 13:34:12 -0500
NoMethodError: machine[druid_ci] (@recipe_files::/cookbooks/openstack/cluster.rb line 14) had an error: NoMethodError: undefined method `empty?' for nil:NilClass
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.1.0/lib/chef/provisioning/convergence_strategy/install_sh.rb:67:in `setup_convergence'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.1.0/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.1.0/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/provider.rb:145:in `run_action'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource.rb:561:in `run_action'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:49:in `run_action'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `each'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `block in converge'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:80:in `converge'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:331:in `block in converge'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:326:in `catch'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:326:in `converge'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:345:in `converge_and_save'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:449:in `run'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:271:in `block in fork_chef_client'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:259:in `fork'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:259:in `fork_chef_client'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:225:in `block in run_chef_client'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:213:in `run_chef_client'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:382:in `loop'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:372:in `run_application'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:60:in `run'
/Users/bslim/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/bin/chef-client:26:in `<top (required)>'
/Users/bslim/.chefdk/gem/ruby/2.1.0/bin/chef-client:23:in `load'
/Users/bslim/.chefdk/gem/ruby/2.1.0/bin/chef-client:23:in `<main>'
```

chef-client run output

```
NoMethodError
    -------------
    undefined method `empty?' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In /user/bslim/openstack/cluster.rb

     14: machine 'druid_ci'
     15:

    Compiled Resource:
    ------------------
    # Declared in /user/bslim/openstack/cluster.rb:14:in `from_file'

    machine("druid_ci") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"https://chef.ops.org.com/organizations/data_platforms_and_systems_druid", :options=>{:client_name=>"bslim", :signing_key_filename=>"/Users/bslim/bslim.pem"}}
      driver "fog:OpenStack"
      machine_options {:bootstrap_options=>{:image_ref=>"3c1d9bcc-7bfe-4096-b12e-68759d5b4264", :flavor_ref=>"1000", :name=>"druid_base", :user_id=>"d_druid", :key_path=>"/Users/bslim/.ssh/d_druid_rsa"}, :ssh_username=>"d_druid", :no_network=>true}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/user/bslim/openstack/openstack/cluster.rb"
    end
```

my driver options

``` ruby
driver 'fog:OpenStack'
driver_options :compute_options => {
                 :openstack_username => 'd_druid',
                 :openstack_api_key => 'password',
                 :openstack_auth_url => 'http://keystone-service.openstack.gq1.corp.net:5000/v2.0/tokens',
                 :openstack_tenant => 'druid.us'
               }
```

cluster.rb

``` ruby
require 'chef/provisioning'
require 'chef/provisioning/driver_init/fog'

with_machine_options :bootstrap_options => {
                       :image_ref => '3c1d9bcc-7bfe-4096-b12e-68759d5b4264',
                       :flavor_ref => '1000',
                       :name => 'druid_base',
                       :user_id => 'd_druid',
                       :key_path => '/Users/bslim/.ssh/d_druid_rsa'
                     },
                     :ssh_username => 'd_druid',
                     :no_network => true

machine 'druid_ci'
```

**Comment by rmoriz** [comment]
was probably fixed with https://github.com/chef/chef-provisioning/commit/d7438a886a627d069a4ce4e9b59494aa7e93d94e
