### ISSUE TITLE
Merge fails in convergence_strategy/install_cached if convergence_options is nill

### ISSUE THREAD

**Issue by elliott-davis** [chef/chef-provisioning#331]
When calling ready_machine with convergence_options undefined, convergence_strategy/install_cached.rb dies due to cheffish being unable to merge a nill hash.

```
Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/cheffish-1.1.2/lib/cheffish/merged_config.rb:27:in `block in []': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/cheffish-1.1.2/lib/cheffish/merged_config.rb:26:in `each'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/cheffish-1.1.2/lib/cheffish/merged_config.rb:26:in `[]'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/convergence_strategy/install_cached.rb:29:in `initialize'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vagrant-0.8.3/lib/chef/provisioning/vagrant_driver/driver.rb:382:in `new'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vagrant-0.8.3/lib/chef/provisioning/vagrant_driver/driver.rb:382:in `convergence_strategy_for'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vagrant-0.8.3/lib/chef/provisioning/vagrant_driver/driver.rb:369:in `machine_for'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vagrant-0.8.3/lib/chef/provisioning/vagrant_driver/driver.rb:74:in `ready_machine'
	from embed.rb:42:in `block in <main>'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/chef-12.2.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /Users/elliottdavis/.chefdk/gem/ruby/2.1.0/gems/cheffish-1.1.2/lib/cheffish.rb:65:in `honor_local_mode'
	from embed.rb:37:in `<main>'
```

Script to reproduce:

```
#!/usr/bin/env ruby

require 'rubygems'
require 'chef/provisioning'
require 'chef/knife'
require 'chef/run_context'
require 'chef/server_api'
require 'chef/provisioning/action_handler'
require 'chef/provisioning/version'
require 'chef/provisioning/machine_spec'

chef_config = {
  driver: 'vagrant',
  machine_options: { vagrant_options: { 'vm.box' => 'ubuntu1404' } },
  node_name: 'elliott',
  log_level: :debug,
  local_mode: true
}

def action_handler
  @action_handler ||= ActionHandler.new
end

class ActionHandler < Chef::Provisioning::ActionHandler
  def recipe_context
    # TODO: somehow remove this code; should context really always be needed?
    node = Chef::Node.new
    node.name 'nothing'
    node.automatic[:platform] = 'provisioning'
    node.automatic[:platform_version] = Chef::Provisioning::VERSION
    Chef::RunContext.new(node, {},
      Chef::EventDispatch::Dispatcher.new(Chef::Formatters::Doc.new(STDOUT,STDERR)))
  end
end

Cheffish.honor_local_mode do
  machine_spec = Chef::Provisioning.chef_managed_entry_store().new_entry(:machine, chef_config[:node_name])
  driver = Chef::Provisioning.default_driver(chef_config)
  machine_options = driver.config[:machine_options]
  driver.allocate_machine(action_handler, machine_spec, machine_options)
  driver.ready_machine(action_handler, machine_spec, machine_options)
end
```

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
