### ISSUE TITLE
OpenSSL issue with chef provisioning

### ISSUE THREAD

**Issue by AnanthRavi** [chef/chef-provisioning#343]
Hey,
I'm having issues using chef-provisioning with the aws driver. It seems to work for one AWS account but fails on the other. 
This is the stacktrace:
```
Generated at 2015-05-20 11:20:12 -0700
OpenSSL::SSL::SSLError: machine[webtest-chef-1] (zsf_testpads::testpads_provision line 22) had an error: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:583:in `start'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:478:in `get_response'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:455:in `get'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/convergence_strategy/install_sh.rb:68:in `setup_convergence'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-provisioning-1.1.1/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/client.rb:339:in `block in converge'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/client.rb:334:in `catch'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/client.rb:334:in `converge'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/client.rb:353:in `converge_and_save'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/client.rb:457:in `run'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application.rb:271:in `block in fork_chef_client'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork_chef_client'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application.rb:225:in `block in run_chef_client'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application.rb:213:in `run_chef_client'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `loop'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application/client.rb:382:in `run_application'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/lib/chef/application.rb:60:in `run'
/Users/ananthravi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.3.0/bin/chef-client:26:in `<top (required)>'
/Users/ananthravi/.rbenv/versions/2.2.1/bin/chef-client:23:in `load'
```

**Comment by rmoriz** [comment]
I'm having the same issue with chef-provisioning-google. 

```
Net::HTTP.get(URI('https://www.chef.io/chef/install.sh'))
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

```
Net::HTTP.get(URI('https://chef.io/chef/install.sh'))
=> "<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by rmoriz** [comment]
Turned out chefdk worked fine because it includes an old cacert.pem bundle from Mozilla, which seems to work.

read "RSA-1024 removed" in http://curl.haxx.se/docs/caextract.html

I was able to fix the problem by replacing /usr/local/etc/openssl/cert.pem with the contents of
https://raw.githubusercontent.com/bagder/ca-bundle/e9175fec5d0c4d42de24ed6d84a06d504d5e5a09/ca-bundle.crt

**Comment by AnanthRavi** [comment]
Also this issue happens only on my Mac (OS X Yosemite), works fine with Ubuntu, Amazon Linux.

**Comment by tyler-ball** [comment]
@rmoriz What version of the ChefDK are you using?  We have someone on our team who is running into this issue _only_ while using the ChefDK and not using rbenv.

**Comment by rmoriz** [comment]
@tyler-ball actually I'm not using ChefDK, I just installed it to see if it works. As ChefDK uses the "old" Mozilla Root, which is already a couple of months old, maybe you're missing some new roots?

**Comment by metadave** [comment]
Running an OSX update via the app store resolved the issue for me. Thanks @tyler-ball

**Comment by rmoriz** [comment]
@metadave strange. AFAIK ChefDK should not share any certificate dependencies with OSX?

**Comment by metadave** [comment]
@rmoriz not that I'm aware of for the ChefDK, but it looks like Ruby does.

@AnanthRavi If all the issues reported here are for OSX Yosemite, I'd like to see if updating via the App Store helps and then close the issue.

**Comment by rmoriz** [comment]
@metadave ChefDK includes a Ruby, OpenSSL and a mozilla root with 1024bit CA keys (recent releases). Its Ruby is linked to the included OpenSSL so everything should work out of the box. If you're using system ruby, rbenv, rvm etc. and/or homebrew's `openssl` together with `link --force` it get's really complicated…

**Comment by AnanthRavi** [comment]
I'm still running into the same issue, updating via the App store didn't help. Does rvm mess something up?

**Comment by metadave** [comment]
@AnanthRavi You can try https://rvm.io/support/fixing-broken-ssl-certificates
You'll need to su to root, run `chef shell-init`, and then follow the commands in the link

**Comment by tyler-ball** [comment]
@AnanthRavi if you open Keychain Access (the app) and look at your System Certificates, do you only have 2 listed?  One of my previous issues was that I had a 3rd cert in the list breaking stuff.

**Comment by metadave** [comment]
@tyler-ball I still have 3 including the `Apple Worldwide Developer Relations Certification Authority` cert

**Comment by AnanthRavi** [comment]
@tyler-ball I have about 6 certificates under System -> Certificates. Some of which I can't remove.

**Comment by metadave** [comment]
@AnanthRavi what's the exact version of OSX that you are using? Also, if you haven't already, can you try the same w/ the ChefDK using the commands `chef shell-init`? rvm may be an issue here.

**Comment by AnanthRavi** [comment]
That solved the issue. Thank you so much, also I updated to the latest version of ChefDK. 
 @metadave

**Comment by metadave** [comment]
excellent!

**Comment by RogerJoys** [comment]
I had to use the updated cert.pem referenced above, but it needed to be in /etc/openssl in my case (on OSX)
