### ISSUE TITLE
install_sh.rb has an issue with bootstrap

### ISSUE THREAD

**Issue by shubhamitc** [chef/chef-provisioning#380]
###########################################################################

version : chefDK 0.4.3 
Chef-client : chef-12.3.0
Chef-provision : latest

###########################################################################
Recipe 

```
require 'chef/provisioning'
#fog_key_pair 'ZlabsCDH'

with_driver 'fog:AWS', :compute_options => { :aws_access_key_id => '***', :aws_secret_access_key => '***', :region => 'us-east-1', :private_key => 'ssh.pem'}

with_machine_options :bootstrap_options => {
  :key_name => 'ZlabsCDH',
  :image_id => 'ami-59a4a230',
  :flavor_id => 't1.micro'
}

machine 'singhis1234' do
file '/etc/chef/trusted_certs/ec2-54-210-74-64_compute-1_amazonaws_com.crt' , 'trusted_certs/ec2-54-210-74-64_compute-1_amazonaws_com.crt'
end

```

===========================================================================

Stack trace

```
INFO: Executing sudo chef-client -v on ubuntu@54.209.90.251
sudo: chef-client: command not found
[2015-07-01T21:28:44+05:30] INFO: Completed chef-client -v on ubuntu@54.209.90.251: exit status 1
[2015-07-01T21:30:52+05:30] DEBUG: Closing SSH session on ubuntu@54.209.90.251

    
    ================================================================================
    Error executing action `converge` on resource 'machine[singhis1234]'
    ================================================================================
    
    Errno::ETIMEDOUT
    ----------------
    Connection timed out - connect(2) for "www.chef.io" port 443
    
    Resource Declaration:
    ---------------------
    # In /home/breeze/aws.rb
    
     15: machine 'singhis1234' do
     16: file '/etc/chef/trusted_certs/ec2-54-210-74-64_compute-1_amazonaws_com.crt' , '/home/breeze/workspace/keys/trusted_certs/ec2-54-210-74-64_compute-1_amazonaws_com.crt'
     17: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/breeze/aws.rb:15:in `from_file'
    
    machine("singhis1234") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"https://ec2-54-210-74-64.compute-1.amazonaws.com/organizations/itc", :options=>{:client_name=>"singh", :signing_key_filename=>"/home/breeze/workspace/keys/singh.pem"}}
      driver "fog:AWS"
      machine_options {:bootstrap_options=>{:key_name=>"ZlabsCDH", :image_id=>"ami-59a4a230", :flavor_id=>"t1.micro"}}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/home/breeze/aws.rb"
      files {"/etc/chef/trusted_certs/ec2-54-210-74-64_compute-1_amazonaws_com.crt"=>"/home/breeze/workspace/keys/trusted_certs/ec2-54-210-74-64_compute-1_amazonaws_com.crt"}
    end
    
[2015-07-01T21:30:52+05:30] INFO: Running queued delayed notifications before re-raising exception
[2015-07-01T21:30:52+05:30] DEBUG: Re-raising exception: Errno::ETIMEDOUT - machine[singhis1234] (@recipe_files::/home/breeze/aws.rb line 15) had an error: Errno::ETIMEDOUT: Connection timed out - connect(2) for "www.chef.io" port 443
/home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:879:in `open'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:878:in `connect'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:852:in `start'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:583:in `start'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:478:in `get_response'
  /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:455:in `get'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-provisioning-1.2.0/lib/chef/provisioning/convergence_strategy/install_sh.rb:68:in `setup_convergence'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-provisioning-1.2.0/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/client.rb:339:in `block in converge'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/client.rb:334:in `catch'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/client.rb:334:in `converge'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/client.rb:353:in `converge_and_save'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/client.rb:457:in `run'
  /home/breeze/.rvm/gems/ruby-2.1.1@zicos/gems/chef-12.3.0/lib/chef/application.rb:271:in `block in fork_chef_client'
```

==============================================================================

It seems that issue is there with Net::HTTP.get while fetching the code.
IRB code 

```
a = Net::HTTP.get(URI('https://chef.io/chef/install.sh'))
Errno::ETIMEDOUT: Connection timed out - connect(2) for "chef.io" port 443
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:879:in `open'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:878:in `connect'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:852:in `start'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:583:in ` start'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:478:in `get_response'
from /home/breeze/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:455:in `get'​
```

Local workstation has http proxy, that might be any issue.

**Comment by tyler-ball** [comment]
Updating to ChefDK 0.7.0 (which includes Mixlib::Install in chef-provisining) fixes this issue.  Please re-open if you still see this with the latest ChefDK!
