### ISSUE TITLE
omnibus commandline over winrm  is too long

### ISSUE THREAD

**Issue by hh** [chef/chef-provisioning#431]
When provisioning windows boxes with the winrm omnibus installer we get an error ```
STDERR: The command line is too long. 
```

# The tail output from the chef-client run on the provisioner:

```
    - create directory \etc\chef\ohai\hints on windows1
    - write file /etc/chef/ohai/hints/ec2.json on windows1
    - write file C:\chef\client.rb on windows1
    ================================================================
    Error executing action `converge` on resource 'machine[windows1]'
    ================================================================
    
    RuntimeError
    ------------
    Error: command '
    $chef_omnibus_root = "$env:systemdrive\opscode\chef"
    $msi = "$env:TEMP\chef-latest.msi"
    $chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
    $pretty_version = "always install latest version"
    $version = "latest"
    
    Function Check-UpdateChef($root, $version) {
      if (-Not (Test-Path $root)) { return $true }
      elseif ("$version" -eq "true") { return $false }
      elseif ("$version" -eq "latest") { return $true }
    
      Try { $chef_version = Get-Content $root\version-manifest.txt | select-object -1}
      Catch {
        Try { $chef_version = (& $root\bin\chef-solo.bat -v).split(" ", 2)[1] }
        Catch { $chef_version = "" }
      }
    
      if ($chef_version.StartsWith($version)) { return $false }
      else { return $true }
    }
    
    Function Get-ChefMetadata($url) {
      Try { $response = ($c = Make-WebClient).DownloadString($url) }
      Finally { if ($c -ne $null) { $c.Dispose() } }
    
      $md = ConvertFrom-StringData $response.Replace("`t", "=")
      return @($md.url, $md.md5)
    }
    
    Function Get-MD5Sum($src) {
      Try {
        $c = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
        $bytes = $c.ComputeHash(($in = (Get-Item $src).OpenRead()))
        return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLower()
      } Finally { if (($c -ne $null) -and ($c.GetType().GetMethod("Dispose") -ne $null)) { $c.Dispose() }; if ($in -ne $null) { $in.Dispose() } }
    }
    
    Function Download-Chef($url, $md5, $dst) {
      Try {
        Log "Downloading package from $url"
        ($c = Make-WebClient).DownloadFile($url, $dst)
        Log "Download complete."
      } Finally { if ($c -ne $null) { $c.Dispose() } }
    
      if ($md5 -eq $null) { Log "Skipping md5 verification" }
      elseif (($dmd5 = Get-MD5Sum $dst) -eq $md5) { Log "Successfully verified $dst" }
      else { throw "MD5 for $dst $dmd5 does not match $md5" }
    }
    
    Function Install-Chef($msi) {
      Log "Installing Chef Omnibus package $msi"
      $p = Start-Process -FilePath "msiexec.exe" -ArgumentList "/qn /i $msi" -Passthru -Wait
    
      if ($p.ExitCode -ne 0) { throw "msiexec was not successful. Received exit code $($p.ExitCode)" }
    
      Remove-Item $msi -Force
      Log "Installation complete"
    }
    
    Function Log($m) { Write-Host "       $m`n" }
    
    Function Make-WebClient {
      $proxy = New-Object -TypeName System.Net.WebProxy
      $proxy.Address = $env:http_proxy
      $client = New-Object -TypeName System.Net.WebClient
      $client.Proxy = $proxy
      return $client
    }
    
    Function Unresolve-Path($p) {
      if ($p -eq $null) { return $null }
      else { return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($p) }
    }
    
    $chef_omnibus_root = Unresolve-Path $chef_omnibus_root
    $msi = Unresolve-Path $msi
    
    if (Check-UpdateChef $chef_omnibus_root $version) {
      Write-Host "-----> Installing Chef Omnibus ($pretty_version)`n"
      if ($chef_metadata_url -ne $null) {
        $url, $md5 = Get-ChefMetadata "$chef_metadata_url"
      } else {
        $url = $chef_msi_url
        $md5 = $null
      }
      Download-Chef "$url" $md5 $msi
      Install-Chef $msi
    } else {
      Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
    }
    ' exited with code 1.
    STDOUT: STDERR: The command line is too long.
    
    Resource Declaration:
    ---------------------
    # In /home/hh/chef-repo/cookbooks/starter/recipes/new.rb
    
     17: machine 'windows1' do
     18:   machine_options({
     19:                     security_group_ids: 'inbound_winrm_rdp_web'
     20:                   })
     21: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/hh/chef-repo/cookbooks/starter/recipes/new.rb:17:in `from_file'
    
    machine("windows1") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"https://api.chef.io/organizations/vulk-stratalux", :options=>{:client_name=>"wolfpack", :signing_key_filename=>"/home/hh/chef-repo/.chef/wolfpack.pem", :api_version=>"0"}}
      driver "aws::us-west-2"
      machine_options {:security_group_ids=>"inbound_winrm_rdp_web"}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/home/hh/chef-repo/cookbooks/starter/recipes/new.rb"
    end
    
[2015-09-06T10:25:40-04:00] INFO: Running queued delayed notifications before re-raising exception
```

# Stacktrace:

```
Generated at 2015-09-06 10:25:40 -0400
RuntimeError: machine[windows1] (@recipe_files::/home/hh/chef-repo/cookbooks/starter/recipes/new.rb line 17) had an error: RuntimeError: Error: command '
... (command from above)
  Write-Host "-----> Chef Omnibus installation detected ($pretty_version)`n"
}
' exited with code 1.
STDOUT: STDERR: The command line is too long.

/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/transport/winrm.rb:146:in `error!'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/machine/basic_machine.rb:31:in `block in execute'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/mixin/why_run.rb:52:in `call'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider.rb:175:in `converge_by'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/chef_provider_action_handler.rb:54:in `perform_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/machine/basic_machine.rb:29:in `execute'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/convergence_strategy/install_msi.rb:39:in `setup_convergence'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:46:in `block in action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider.rb:140:in `run_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource.rb:584:in `run_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:49:in `run_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `each'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block in converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:80:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:654:in `block in converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `catch'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:688:in `converge_and_save'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:269:in `run'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:224:in `block in run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:212:in `run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `loop'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:382:in `run_application'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:60:in `run'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/bin/chef-client:26:in `<top (required)>'
/home/hh/.rvm/gems/ruby-2.2.0/bin/chef-client:23:in `load'
/home/hh/.rvm/gems/ruby-2.2.0/bin/chef-client:23:in `<main>'
/home/hh/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/hh/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by hh** [comment]
The command looks to be under 7k, so CreateProcess should be happy (32k limit) http://blogs.msdn.com/b/oldnewthing/archive/2003/12/10/56028.aspx

**Comment by hh** [comment]
knife-windows/issues/262 is seeing the same thing.... it may be specific to windows 2012

**Comment by hh** [comment]
Looking into debugging the [write_file function](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/transport/winrm.rb#L55) function:

```ruby
      def write_file(path, content)
        chunk_size = options[:chunk_size] || 1024
        # TODO if we could marshal this data directly, we wouldn't have to base64 or do this godawful slow stuff :(
        index = 0
        execute("
$ByteArray = [System.Convert]::FromBase64String(#{escape(Base64.encode64(content[index..index+chunk_size-1]))})
$file = [System.IO.File]::Open(#{escape(path)}, 'Create', 'Write')
$file.Write($ByteArray, 0, $ByteArray.Length)
$file.Close
").error!
        index += chunk_size
        while index < content.length
          execute("
$ByteArray = [System.Convert]::FromBase64String(#{escape(Base64.encode64(content[index..index+chunk_size-1]))})
$file = [System.IO.File]::Open(#{escape(path)}, 'Append', 'Write')
$file.Write($ByteArray, 0, $ByteArray.Length)
$file.Close
").error!
          index += chunk_size
        end
      end
```

**Comment by hh** [comment]
Going to try a smaller check_size (though it does appear to be breaking on the last check).

**Comment by hh** [comment]
I'm not seeing a way to configure chunk_size other than by editing the src https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L813

It would need to be set in the winrm_options hash which doesn't seem to have keys merged in from anywhere:

```ruby
      winrm_options = {
        :user => machine_spec.reference['winrm_username'] || 'Administrator',
        :pass => decrypted_password,
        :disable_sspi => true,
        :basic_auth_only => true
      }

      Chef::Provisioning::Transport::WinRM.new("#{endpoint}", type, winrm_options, {})
```

**Comment by hh** [comment]
It's not write_file that's hurting us, it's the install_command string from [convergence_strategy install_msi](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_msi.rb#L38).

```ruby
        install_command = Mixlib::Install.new(chef_version, true, opts).install_command
        machine.execute(action_handler, install_command)
```

In by debugging the install_command length is 3059, we should probably chunk that out or make it smaller.

```
[34, 43] in /home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/convergence_strategy/install_msi.rb
   34:         end
   35:         opts["install_msi_url"] = convergence_options[:install_msi_url] if convergence_options[:install_msi_url]
   36:         super
   37: 
   38:         install_command = Mixlib::Install.new(chef_version, true, opts).install_command
=> 39:         machine.execute(action_handler, install_command)
   40:       end
   41: 
   42:       def converge(action_handler, machine)
   43:         super
(byebug) install_command.length
3059
```

**Comment by Angelicvorian** [comment]
Guys, not sure if this helps, but i was getting this error, near the start of the bootstrap "Command Line too long".
I've been playing with SSL being enabled on WinRM and during this i upgraded the knife-windows gem to version 1.0.0
I've now reversed out knife-windows 1.0.0 so it is using 0.8.4 and bootstrap now proceeds as normal.
I was bootstrapping a Windows 2008 R2 standard server.

**Comment by ksubrama** [comment]
I ended up digging into this and discovered the root cause tying https://github.com/chef/knife-windows/issues/262 and https://github.com/chef/mixlib-install/issues/6 and https://github.com/chef/chef-provisioning/issues/431 and https://github.com/test-kitchen/test-kitchen/issues/811.  The ~3060 character limit is not fundamental to powershell.  The command length is still 8191 bytes.  But the way winrm commands are being run are through https://github.com/WinRb/WinRM/blob/master/lib/winrm/helpers/powershell_script.rb.  The script is first expanded as a UTF16-LE string and then base64 encoded.  Base64 produces 4 bytes of output for every 3 bytes of input.  If we use ~30 characters or so to frame the command (such as "powershell.exe -encodedcommand ..."), then:  (8191-30)*3/4 *1/2 is 3060.  Using the full path of powershell or passing additional arguments will only lower that limit.

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
