### ISSUE TITLE
1.4.1: Deprecated features in use; retired in Chef 13

### ISSUE THREAD

**Issue by yvovandoorn** [chef/chef-provisioning#462]
Currently the latest release of Provisioning 1.4.1 fires off 4 alerts at the end of a Chef Client run (12.5.1) notifying the user of deprecated features in use:

```
  output_key_path nil currently does not overwrite the value of output_key_path. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :output_key_path, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.4.1/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:148:in `block (2 levels) in create_chef_objects'
  output_key_format nil currently does not overwrite the value of output_key_format. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :output_key_format, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.4.1/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:149:in `block (2 levels) in create_chef_objects'
  admin nil currently does not overwrite the value of admin. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :admin, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.4.1/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:150:in `block (2 levels) in create_chef_objects'
  validator nil currently does not overwrite the value of validator. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :validator, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.4.1/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:151:in `block (2 levels) in create_chef_objects'
  encrypt nil currently does not overwrite the value of encrypt. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "pr
```

**Comment by epsilon-jpage** [comment]
I'm getting the exact same.

**Comment by yoshiwaan** [comment]
Everyone will get this as those error messages were introduced in a recent version of Chef (12.X, I forget exactly which). 

It's good to have this issue to remind developers about the deprecation but it's nothing to worry about.

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
