### ISSUE TITLE
machine_execute NoMethodError wish vsphere driver

### ISSUE THREAD

**Issue by Brunzer** [chef/chef-provisioning#514]
I've got a little recipe where I'm trying to execute a simple command on a remote host running on vsphere using machine_execute, but I continuously get a NoMethodError 'undefined method `[]' for nil:NilClass' when it goes to run.

The node itself is created already and everything is fine with it. knife node show gives me all usual information (ie. name, ip, runlist, etc), but this execution still fails.

Here's the recipe (this is a small test recipe from an already created and chef-provisioned VM):
```
require 'chef/provisioning/vsphere_driver'

with_vsphere_driver host: VsphereHost,
  insecure: true,
  user:     VsphereUsername,
  password: VspherePass
with_machine_options ssh_username: 'ubuntu',
	bootstrap_options: {
            num_cpus: 1,
            memory_mb: 1024,
            network_name: ["somenetwork"],
            datacenter: "mydc",
            resource_pool: "mycluster",
            template_name: 'Ubuntu',
            customization_spec: {
              :domain => "somedomain"
            },
            :ssh => {
              :user => 'ubuntu',
              :password => "mypass",
              :paranoid => false,
           }
       }

machine_execute "touch ~/test.txt" do
	machine "node001"
end
```

Here's the full stack trace from the error:
```
Generated at 2016-04-22 19:34:40 +0000
NoMethodError: machine_execute[touch ~/test.txt.txt] (@recipe_files::/home/ubuntu/Admin_Scripts/chef-provisioning/vmware/test.rb line 11) had an error: NoMethodError: undefined method `[]' for nil:NilClass
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:568:in `machine_for'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:381:in `connect_to_machine'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provisioning.rb:98:in `connect_to_machine'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provisioning/chef_run_data.rb:93:in `connect_to_machine'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine_execute.rb:24:in `machine'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine_execute.rb:30:in `block in <class:MachineExecute>'
(eval):2:in `block in action_run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:360:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:144:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource.rb:596:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:73:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:104:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:668:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:702:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:280:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:211:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:412:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:58:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:50:in `load'
/usr/bin/chef-client:50:in `<main>'
```

I've been able to use machine_execute in the past with the fog driver, but haven't had any success in multiple attempts using the vsphere driver. 
Are there known issues with machine_execute not able to obtain access or info from vsphere to execute commands using this resource?

I'm currently using:
```
$ chef gem list | grep chef
chef (12.7.2)
chef-config (12.7.2)
chef-dk (0.11.2)
chef-provisioning (1.6.0)
chef-provisioning-aws (1.8.0)
chef-provisioning-azure (0.5.0)
chef-provisioning-fog (0.16.0)
chef-provisioning-vagrant (0.11.0)
chef-provisioning-vsphere (0.8.4)
chef-vault (2.8.0)
chef-zero (4.5.0)
cheffish (2.0.1)
chefspec (4.5.0)
```

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
